Repository Uliga/Uliga_Frontend, pull requests merged in 2023-05, with the labels that each got.

#62 ULIGA-189 Cypress CI 설정
  cypress.config.ts
  cypress/support/e2e.ts
  package.json
  reporter-config.json
  yarn.lock
Labels: Test

#63 ULIGA-197 소셜 로그인 로직 개선
  src/api/auth.ts
  src/api/config.ts
  src/components/Book/Landing/sns.tsx
  src/hooks/useSocialSignup.ts
  src/pages/social/index.tsx
Labels: Feat, Refactor

#65 ULIGA-183 가계부 내역 페이지 e2e 테스트 코드 작성
  cypress/e2e/3-write-page/write.spec.cy.ts
  cypress/e2e/4-history-page/history.spec.cy.ts
  src/components/Book/History/editForm.tsx
Labels: Test

#66 ULIGA-184 금융 일정 페이지 e2e 테스트 코드 작성
  cypress/e2e/4-history-page/history.spec.cy.ts
  cypress/e2e/5-schedule-page/schedule.spec.cy.ts
  src/components/Book/Schedule/addPrivate/currentList.tsx
  src/components/Book/Schedule/addPrivate/index.tsx
  src/components/Book/Schedule/editPrivate/form.tsx
  src/components/Book/Schedule/editPrivate/index.tsx
Labels: Test

#67 ULIGA-186 예산페이지, 내 정보 수정 e2e 테스트 코드 구현
  cypress/e2e/6-budget-page/budget.spec.cy.ts
  cypress/e2e/7-setting-page/me.spec.cy.ts
  cypress/fixtures/memberInfo.json
Labels: Test

#69 ULIGA-176 비밀번호 초기화, 재설정 구현
  src/api/auth.ts
  src/api/config.ts
  src/components/Button/index.tsx
  src/components/IconButton/index.tsx
  src/hooks/book/useMe.ts
  src/hooks/useLogin.ts
  src/pages/login/index.styles.tsx
  src/pages/login/index.tsx
  src/pages/setting/me/index.tsx
  src/stores/atoms/context.ts
Labels: Feat
